---
title: Cold Standby genereert "DataStoreException Record bestaat niet"
description: Beschrijving
solution: Experience Manager
product: Experience Manager
applies-to: Experience Manager
keywords: KCS,AEM,coldstandby,DataStoreException
resolution: Resolution
internal-notes: https://issues.apache.org/jira/browse/OAK-8202,https://jira.corp.adobe.com/browse/GRANITE-11668
bug: false
article-created-by: Vincent Frey
article-created-date: 5/12/2022 3:39:59 PM
article-published-by: Vincent Frey
article-published-date: 5/12/2022 3:40:16 PM
version-number: 2
article-number: KA-15610
dynamics-url: https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=8e6000c7-09d2-ec11-a7b5-0022480a8683
exl-id: d37d0338-be4f-4660-a4b2-cd1179717e07
source-git-commit: e8f4ca2dd578944d4fe399074fab461de88ad247
workflow-type: tm+mt
source-wordcount: '311'
ht-degree: 0%

---

# Cold Standby genereert &quot;DataStoreException Record bestaat niet&quot;

## Beschrijving


<b>Probleem:</b>
Koude stand-by met toegewezen bestand Datastore geeft een waarschuwing voor ontbrekende blokkering, zoals bij 1.

<b>Details:</b>
Dit is slechts een waarschuwing, geen fout. Het komt uit het feit dat datastore geen manier heeft om te verifiëren of een binair getal plaatselijk bestaat, behalve door blob identiteitskaart te proberen te laden.
Als de id wordt geladen, wordt deze waarschuwing niet weergegeven in de logboeken. Als het echter niet wordt gevonden, weet de stand-by dat het moet worden gesynchroniseerd, dus zien we waarschuwing 1 in de logboeken.


1: *\*WARN\* standby-run-1 org.apache.jackrabbit.oak.plugins.blob.datastore.DataStoreBlobStore Fout opgetreden tijdens het laden van bytes vanuit stoom terwijl het ophalen voor id f68a92b34779bbd194184251ec9 16370f3ebd301d6e32a8980aad070d57a1845#25522
<br>java.util.concurrent.ExecutionException: java.io.IOException: org.apache.jackrabbit.core.data.DataStoreException: Record f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a18 45 bestaat niet
<br>    op org.apache.jackrabbit.oak.cacheLIRS$Segment.load(CacheLIRS.java:1017) org.apache.jackrabbit.oak-core-spi:1.10.3
<br>...
<br>Veroorzaakt door: org.apache.jackrabbit.core.data.DataStoreException: Record cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20 bestaat niet
<br>    op org.apache.jackrabbit.core.data.AbstractDataStore.getRecord(AbstractDataStore.java:59)*


## Resolutie


Dit werkt zoals ontworpen en geeft geen probleem aan met de File DataStore.

<b>Bevestigen:</b>

- Monsterblob-id dat in de stammen voorkomt: &quot;cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c 20 inch
- Voor deze blob-id moet het bestandssysteemadres zijn: &quot;ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c 49c20&quot;
- Zoek het bestandssysteem in een zelfstandige instantie en controleer of het benoemde bestand aanwezig is in de datastore.
- Gebruik in /repository/datastore de opdracht list (ls -ald): &quot;ls -ald ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f193 5a2c49c20&quot;
- U moet het bestand kunnen zien en kunnen bevestigen dat de blob-id eigenlijk niet ontbreekt
