---
title: Cold Standby genereert de fout "DataStoreException Record does not exist"
description: Beschrijving
solution: Experience Manager
product: Experience Manager
applies-to: Experience Manager
keywords: KCS, AEM, cold standby, DataStoreException, Adobe Experience Manager, record bestaat niet, error, warn, warning
resolution: Resolution
internal-notes: https://issues.apache.org/jira/browse/OAK-8202,https://jira.corp.adobe.com/browse/GRANITE-11668
bug: false
article-created-by: Jim Menn
article-created-date: 9/28/2022 2:23:47 PM
article-published-by: Jim Menn
article-published-date: 9/28/2022 5:41:23 PM
version-number: 3
article-number: KA-15610
dynamics-url: https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=5e521024-393f-ed11-9db1-0022480866ad
exl-id: d37d0338-be4f-4660-a4b2-cd1179717e07
source-git-commit: 9c971ee2ceef8f48902d857145545ef173f3752a
workflow-type: tm+mt
source-wordcount: '231'
ht-degree: 0%

---

# Cold Standby genereert de fout &quot;DataStoreException Record does not exist&quot;

## Beschrijving


<b>Omgeving</b>
Adobe Experience Manager

<b>Probleem</b>
Cold Standby met toegewezen File Datastore geeft een waarschuwing voor ontbrekende blob-id die lijkt op de fout hier:


```
*WARN* standby-run-1 org.apache.jackrabbit.oak.plugins.blob.datastore.DataStoreBlobStore Error occurred while loading bytes from steam while fetching for id f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845#25522

java.util.concurrent.ExecutionException: java.io.IOException: org.apache.jackrabbit.core.data.DataStoreException: Record f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845 does not exist

    at org.apache.jackrabbit.oak.cache.CacheLIRS$Segment.load(CacheLIRS.java:1017) org.apache.jackrabbit.oak-core-spi:1.10.3

...

Caused by: org.apache.jackrabbit.core.data.DataStoreException: Record cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20 does not exist

    at org.apache.jackrabbit.core.data.AbstractDataStore.getRecord(AbstractDataStore.java:59)
```


<b>Oorzaak</b>
Dit is slechts een waarschuwing, geen fout.

Het komt uit het feit dat de Datastore van het Dossier geen manier heeft om te verifiëren of een binair getal plaatselijk bestaat, behalve door te proberen om blob identiteitskaart te laden.
Als de id wordt geladen, wordt deze waarschuwing niet weergegeven in de logboeken.
Maar als het niet gevonden wordt, weet de stand-by dat het het moet synchroniseren, dus dat is waarom je dit soort waarschuwing ziet in de logboeken.


## Resolutie


<b>Oplossing</b>
Dit werkt zoals ontworpen en geeft geen probleem aan met de datastore van het bestand.

Voer de volgende stappen uit om te bevestigen dat de blob-id niet ontbreekt:

1. Neem bijvoorbeeld de voorbeeldblob-id die wordt weergegeven als ontbrekend in de logbestanden (bijvoorbeeld: `cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`).
2. Voor deze blob-id in dit voorbeeld moet het bestandssysteemadres als volgt zijn: `ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`.
3. Zoek het bestandssysteem op de stand-byinstantie en controleer of het benoemde bestand aanwezig is in de datastore van het bestand.
4. Within `/repository/datastore`, gebruikt u de `list` (Bijvoorbeeld: `ls -ald`), opdracht: `ls -ald ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`.
5. U moet het bestand kunnen zien en kunnen bevestigen dat de blob-id eigenlijk niet ontbreekt.
